site_name: pipen
edit_uri: blob/master/docs/
repo_url: https://github.com/pwwang/pipen
repo_name: pwwang/pipen
theme:
    name: 'rtd'
    logo: 'rtd-logo.png'
markdown_extensions:
    - attr_list
    - pymdownx.blocks.admonition
    - pymdownx.blocks.details
    - pymdownx.blocks.tab:
        alternate_style: true
    - pymdownx.superfences:
        preserve_tabs: true
    - toc:
        baselevel: 2
        permalink: true
plugins:
    - search # necessary for search to work
    - mkapi
extra_css:
    - assets/style.css
extra_javascript:
    - assets/script.js
nav:
    - 'Introduction':
      - 'Overview': 'index.md'
    - 'Tutorials':
      - 'Beginner Tutorial': 'tutorials/beginner.md'
      - 'Defining a process': 'defining-proc.md'
      - 'Defining and running a pipeline': 'running.md'
    - 'How-to Guides':
      - 'Templating': 'templating.md'
      - 'Channels': 'channels.md'
      - 'Input and output': 'input-output.md'
      - 'Script': 'script.md'
      - 'Caching': 'caching.md'
      - 'Cloud support': 'cloud.md'
      - 'Error handling': 'error.md'
      - 'Configurations': 'configurations.md'
      - 'Plugins': 'plugin.md'
      - 'Scheduler': 'scheduler.md'
      - 'Process group': 'proc-group.md'
      - 'Command line interface': 'cli.md'
    - 'API': mkapi/api/pipen
    - 'Reference':
      - 'Examples': 'examples.md'
      - 'Change Log': 'CHANGELOG.md'
      - 'Troubleshooting': 'troubleshooting.md'
      - 'Contributing': 'CONTRIBUTING.md'
      - 'Glossary': 'glossary.md'
    - 'Explanation':
      - 'Architecture': 'architecture.md'
