site_name: pipen
edit_uri: blob/master/docs/
repo_url: https://github.com/pwwang/pipen
repo_name: pwwang/pipen
theme:
    name: 'rtd'
    logo: 'rtd-logo.png'
markdown_extensions:
    - attr_list
    - pymdownx.blocks.admonition
    - pymdownx.blocks.details
    - pymdownx.blocks.tab:
        alternate_style: true
    - pymdownx.superfences:
        preserve_tabs: true
    - toc:
        baselevel: 2
        permalink: true
plugins:
    - search # necessary for search to work
    - mkapi
extra_css:
    - assets/style.css
extra_javascript:
    - assets/script.js
nav:
    - 'Introduction': 'index.md'
    - 'Basics': 'basics.md'
    - 'Defining a process': 'defining-proc.md'
    - 'Defining and running a pipeline': 'running.md'
    - 'Templating': 'templating.md'
    - 'Channels': 'channels.md'
    - 'Input and output': 'input-output.md'
    - 'Script': 'script.md'
    - 'Caching': 'caching.md'
    - 'Cloud support': 'cloud.md'
    - 'Error handling': 'error.md'
    - 'Configurations': 'configurations.md'
    - 'Plugins': 'plugin.md'
    - 'Scheduler': 'scheduler.md'
    - 'Process group': 'proc-group.md'
    - 'Command line iterface': 'cli.md'
    - 'Examples': 'examples.md'
    - 'Change log': 'CHANGELOG.md'
    - 'API': mkapi/api/pipen
